# Generated by Django 5.0.1 on 2025-11-30 18:45

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_iso",
                    models.CharField(
                        help_text="Código ISO 3166-1 alpha-2",
                        max_length=2,
                        unique=True,
                        verbose_name="código ISO",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="nome completo"),
                ),
                (
                    "continente",
                    models.CharField(max_length=50, verbose_name="continente"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="longitude"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "país",
                "verbose_name_plural": "países",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PlanoViagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cidade_destino",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="cidade de destino"
                    ),
                ),
                (
                    "regiao_destino",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="região de destino"
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="data de início")),
                ("data_fim", models.DateField(verbose_name="data de término")),
                (
                    "flexibilidade_datas",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se as datas podem ser ajustadas",
                        verbose_name="datas flexíveis",
                    ),
                ),
                (
                    "motivo_viagem",
                    models.CharField(
                        choices=[
                            ("turismo", "Turismo"),
                            ("trabalho", "Trabalho"),
                            ("estudo", "Estudo"),
                            ("voluntariado", "Voluntariado"),
                            ("outro", "Outro"),
                        ],
                        default="turismo",
                        max_length=20,
                        verbose_name="motivo da viagem",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descreva seus planos e interesses para a viagem",
                        max_length=1000,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "nivel_privacidade",
                    models.CharField(
                        choices=[
                            ("publico", "Público - Visível para todos"),
                            ("amigos", "Apenas Amigos"),
                            ("privado", "Privado - Não visível"),
                        ],
                        default="publico",
                        max_length=10,
                        verbose_name="nível de privacidade",
                    ),
                ),
                (
                    "orcamento_diario_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="orçamento mensal mínimo",
                    ),
                ),
                (
                    "orcamento_diario_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="orçamento mensal máximo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "viagem_concluida",
                    models.BooleanField(default=False, verbose_name="viagem concluída"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                (
                    "pais_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_viagem",
                        to="destinos.pais",
                        verbose_name="país de destino",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_viagem",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "plano de viagem",
                "verbose_name_plural": "planos de viagem",
                "ordering": ["-data_inicio"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "ativo"],
                        name="destinos_pl_usuario_d39341_idx",
                    ),
                    models.Index(
                        fields=["pais_destino", "data_inicio"],
                        name="destinos_pl_pais_de_ed8812_idx",
                    ),
                    models.Index(
                        fields=["nivel_privacidade"],
                        name="destinos_pl_nivel_p_61ca4a_idx",
                    ),
                ],
            },
        ),
    ]
