# Generated by Django 5.0.1 on 2025-11-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoviagem",
            name="data_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de término"
            ),
        ),
        migrations.CreateModel(
            name="EnderecoPlano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=30, verbose_name="número"),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=120, verbose_name="bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=120, verbose_name="cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=120, verbose_name="estado"),
                ),
                (
                    "pais_texto",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="país (texto)"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "plano",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endereco_plano",
                        to="destinos.planoviagem",
                        verbose_name="plano de viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "endereço do plano",
                "verbose_name_plural": "endereços dos planos",
            },
        ),
        migrations.CreateModel(
            name="OfertaResidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_anfitriao",
                    models.CharField(max_length=150, verbose_name="nome do anfitrião"),
                ),
                (
                    "contato_anfitriao",
                    models.CharField(
                        max_length=150, verbose_name="contato do anfitrião"
                    ),
                ),
                (
                    "descricao_local",
                    models.TextField(
                        blank=True, verbose_name="descrição da residência"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "plano",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oferta_residencia",
                        to="destinos.planoviagem",
                        verbose_name="plano de viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta de residência",
                "verbose_name_plural": "ofertas de residência",
            },
        ),
    ]
