# Generated by Django 5.0.1 on 2026-01-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinos", "0002_alter_planoviagem_data_fim_enderecoplano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pais",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="paises/",
                verbose_name="imagem do país",
            ),
        ),
    ]
