# Generated by Django 5.0.1 on 2026-03-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinos", "0003_pais_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="planoviagem",
            name="imagens_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de URLs públicas de imagens do destino (máx. 6)",
                verbose_name="URLs de imagens",
            ),
        ),
    ]
