# Generated by Django 5.0.1 on 2026-03-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinos", "0004_planoviagem_imagens_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planoviagem",
            old_name="flexibilidade_datas",
            new_name="datas_flexiveis",
        ),
        migrations.RenameField(
            model_name="planoviagem",
            old_name="orcamento_diario_max",
            new_name="orcamento_mensal_maximo",
        ),
        migrations.RenameField(
            model_name="planoviagem",
            old_name="orcamento_diario_min",
            new_name="orcamento_mensal_minimo",
        ),
        migrations.AlterField(
            model_name="planoviagem",
            name="imagens_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de URLs públicas de imagens do destino (máx. 6). Ex: ["url1", "url2"]',
                verbose_name="URLs de imagens",
            ),
        ),
    ]
