# Generated by Django 5.0.1 on 2026-03-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "destinos",
            "0005_rename_flexibilidade_datas_planoviagem_datas_flexiveis_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planoviagem",
            name="orcamento_mensal_maximo",
        ),
    ]
