# Generated by Django 5.0.1 on 2025-11-30 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amizade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "usuario1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amizades_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário 1",
                    ),
                ),
                (
                    "usuario2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amizades_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "amizade",
                "verbose_name_plural": "amizades",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario1", "ativa"],
                        name="conexoes_am_usuario_1899ce_idx",
                    ),
                    models.Index(
                        fields=["usuario2", "ativa"],
                        name="conexoes_am_usuario_b5433e_idx",
                    ),
                ],
                "unique_together": {("usuario1", "usuario2")},
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoAmizade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mensagem",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem opcional ao enviar solicitação",
                        max_length=500,
                        verbose_name="mensagem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aceita", "Aceita"),
                            ("recusada", "Recusada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_resposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de resposta"
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatário",
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação de amizade",
                "verbose_name_plural": "solicitações de amizade",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["remetente", "status"],
                        name="conexoes_so_remeten_45ae59_idx",
                    ),
                    models.Index(
                        fields=["destinatario", "status"],
                        name="conexoes_so_destina_f986a1_idx",
                    ),
                ],
                "unique_together": {("remetente", "destinatario")},
            },
        ),
    ]
