# Generated by Django 5.0.1 on 2026-03-29 16:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("login_sucesso", "Login bem-sucedido"),
                            ("login_falha", "Falha no login"),
                            ("registro_novo_usuario", "Novo usuário registrado"),
                            ("deletar_usuario", "Usuário deletado"),
                            ("verificar_email", "Email verificado"),
                            ("alterar_senha", "Senha alterada"),
                            ("alterar_perfil", "Perfil alterado"),
                            ("criar_plano_viagem", "Plano de viagem criado"),
                            ("deletar_plano_viagem", "Plano de viagem deletado"),
                            (
                                "solicitacao_amizade_enviada",
                                "Solicitação de amizade enviada",
                            ),
                            ("amizade_aceita", "Amizade aceita"),
                            ("amizade_rejeitada", "Amizade rejeitada"),
                            ("enviar_mensagem", "Mensagem enviada"),
                            ("deletar_mensagem", "Mensagem deletada"),
                            ("acesso_negado_permissao", "Acesso negado - permissão"),
                            (
                                "acesso_negado_autenticacao",
                                "Acesso negado - não autenticado",
                            ),
                            ("acesso_recurso_sensivel", "Acesso a recurso sensível"),
                            (
                                "alteracao_configuracoes",
                                "Configurações do sistema alteradas",
                            ),
                            ("erro_aplicacao", "Erro na aplicação"),
                            ("atividade_suspeita", "Atividade suspeita"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="tipo de ação",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "usuario_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email do usuário"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="user agent"
                    ),
                ),
                (
                    "resultado",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="sucesso"
                    ),
                ),
                (
                    "detalhes_erro",
                    models.TextField(blank=True, verbose_name="detalhes do erro"),
                ),
                (
                    "metodo_http",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        verbose_name="método HTTP",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="endpoint"
                    ),
                ),
                (
                    "codigo_resposta",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="código HTTP"
                    ),
                ),
                (
                    "dados_alterados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON com campos que foram modificados",
                        verbose_name="dados alterados",
                    ),
                ),
                (
                    "requer_investigacao",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag para ações que podem indicar fraude ou abuso",
                        verbose_name="requer investigação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de auditoria",
                "verbose_name_plural": "logs de auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_logaud_timesta_bdeaaf_idx"
                    ),
                    models.Index(
                        fields=["usuario_email", "-timestamp"],
                        name="core_logaud_usuario_4a073e_idx",
                    ),
                    models.Index(
                        fields=["tipo_acao", "-timestamp"],
                        name="core_logaud_tipo_ac_8f496a_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="core_logaud_ip_addr_5252dc_idx",
                    ),
                    models.Index(
                        fields=["requer_investigacao", "-timestamp"],
                        name="core_logaud_requer__eb544b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TentativaLoginFalhado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "email_tentativa",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email da tentativa"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="user agent"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("usuario_nao_existe", "Usuário não existe"),
                            ("senha_incorreta", "Senha incorreta"),
                            ("email_nao_verificado", "Email não verificado"),
                            ("usuario_bloqueado", "Usuário bloqueado"),
                            ("usuario_inativo", "Usuário inativo"),
                            ("outro", "Outro"),
                        ],
                        max_length=100,
                        verbose_name="motivo da falha",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tentativas_login_falhado",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de login falhado",
                "verbose_name_plural": "tentativas de login falhado",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_tentat_timesta_0f4c37_idx"
                    ),
                    models.Index(
                        fields=["email_tentativa", "-timestamp"],
                        name="core_tentat_email_t_f693d6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="core_tentat_ip_addr_c64090_idx",
                    ),
                ],
            },
        ),
    ]
