# Generated by Django 5.0.1 on 2025-11-30 18:34

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Um usuário com este email já existe."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "email_verificado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o email foi verificado.",
                        verbose_name="email verificado",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=150,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="nome completo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de nascimento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Telefone deve estar no formato: "+999999999". Até 15 dígitos permitidos.',
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="telefone",
                    ),
                ),
                (
                    "pais_residencia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="país de residência"
                    ),
                ),
                (
                    "cidade_residencia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="cidade de residência"
                    ),
                ),
                (
                    "biografia",
                    models.TextField(
                        blank=True,
                        help_text="Máximo de 500 caracteres.",
                        max_length=500,
                        verbose_name="biografia",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_perfil/%Y/%m/",
                        verbose_name="foto de perfil",
                    ),
                ),
                (
                    "perfil_publico",
                    models.BooleanField(
                        default=True,
                        help_text="Permite que outros usuários vejam seu perfil.",
                        verbose_name="perfil público",
                    ),
                ),
                (
                    "mostrar_email",
                    models.BooleanField(
                        default=False,
                        help_text="Permite que amigos vejam seu email.",
                        verbose_name="mostrar email",
                    ),
                ),
                (
                    "mostrar_telefone",
                    models.BooleanField(
                        default=False,
                        help_text="Permite que amigos vejam seu telefone.",
                        verbose_name="mostrar telefone",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                (
                    "ultimo_acesso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último acesso"
                    ),
                ),
                (
                    "tentativas_login_falhas",
                    models.IntegerField(
                        default=0, verbose_name="tentativas de login falhas"
                    ),
                ),
                (
                    "bloqueado_ate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bloqueado até"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(fields=["email"], name="usuarios_us_email_41a027_idx"),
                    models.Index(fields=["uuid"], name="usuarios_us_uuid_0ac459_idx"),
                ],
            },
        ),
    ]
