# Generated by Django 5.0.1 on 2025-11-30 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_ultima_mensagem",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data da última mensagem"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "participantes",
                    models.ManyToManyField(
                        related_name="conversas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="participantes",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversa",
                "verbose_name_plural": "conversas",
                "ordering": ["-data_ultima_mensagem"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "conteudo",
                    models.TextField(max_length=2000, verbose_name="conteúdo"),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de envio"
                    ),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="lida")),
                (
                    "data_leitura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de leitura"
                    ),
                ),
                ("editada", models.BooleanField(default=False, verbose_name="editada")),
                (
                    "data_edicao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de edição"
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="chat.conversa",
                        verbose_name="conversa",
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
                "ordering": ["data_envio"],
                "indexes": [
                    models.Index(
                        fields=["conversa", "data_envio"],
                        name="chat_mensag_convers_9fbbb2_idx",
                    ),
                    models.Index(
                        fields=["remetente", "lida"],
                        name="chat_mensag_remeten_3f53c0_idx",
                    ),
                ],
            },
        ),
    ]
